import {defineField, defineType} from 'sanity'
import {isUniqueOtherThanLanguage} from '../lib/isUniqueOtherThanLanguage'

export default defineType({
  name: 'post',
  title: 'Artigo',
  type: 'document',
  groups: [
    {name: 'editorial', title: 'Publicação', default: true},
    {name: 'technical', title: 'Dados técnicos'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Título',
      type: 'string',
      group: 'editorial',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Resumo / Descrição',
      type: 'text',
      group: 'editorial',
      description: 'Resumo usado nos cards, busca e descrição da página. Máximo de 300 caracteres.',
      validation: (Rule) => Rule.required().min(1).max(300),
    }),
    defineField({
      name: 'categories',
      title: 'Categoria',
      type: 'array',
      group: 'editorial',
      of: [{type: 'reference', to: [{type: 'category'}]}],
      validation: (Rule) => Rule.required().min(1).max(1),
    }),
    defineField({
      name: 'thumbnail',
      title: 'Imagem de capa 16:9',
      type: 'image',
      group: 'editorial',
      description: 'Imagem obrigatória para novos artigos. Use formato horizontal 16:9 e sem texto sobre a imagem.',
      fields: [
        defineField({
          name: 'alt',
          title: 'Texto alternativo',
          type: 'string',
          description: 'Descreva brevemente a imagem para acessibilidade.',
        }),
      ],
      options: {hotspot: true},
    }),
    defineField({
      name: 'publishedAt',
      title: 'Data de publicação',
      type: 'datetime',
      group: 'editorial',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'body',
      title: 'Conteúdo',
      type: 'blockContent',
      group: 'editorial',
      description: 'Campo de edição dos novos artigos. As referências e fontes permanecem dentro do próprio texto.',
    }),

    defineField({
      name: 'language',
      title: 'Idioma',
      type: 'string',
      group: 'technical',
      options: {list: [{title: 'Português (Brasil)', value: 'pt-BR'}]},
      initialValue: 'pt-BR',
      validation: (Rule) => Rule.required(),
      readOnly: true,
    }),
    defineField({
      name: 'slug',
      title: 'Endereço do artigo (slug)',
      type: 'slug',
      group: 'technical',
      description: 'Gerado a partir do título. Depois de publicado, deve permanecer estável.',
      options: {source: 'title', maxLength: 96, isUnique: isUniqueOtherThanLanguage},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'coverUrl',
      title: 'URL da capa migrada',
      type: 'url',
      group: 'technical',
      description: 'Preserva a capa dos artigos migrados do Blogger.',
      readOnly: true,
    }),
    defineField({
      name: 'canonicalURL',
      title: 'URL canônica migrada',
      type: 'url',
      group: 'technical',
      readOnly: true,
    }),
    defineField({
      name: 'legacyBodyHtml',
      title: 'Conteúdo legado (HTML)',
      type: 'text',
      group: 'technical',
      description: 'Cópia preservada dos artigos migrados do Blogger. Novos artigos usam o campo Conteúdo.',
      readOnly: true,
    }),
    defineField({
      name: 'author',
      title: 'Autor interno (legado)',
      type: 'reference',
      group: 'technical',
      to: [{type: 'author'}],
      weak: true,
      readOnly: true,
      hidden: ({document}) => !document?.author,
    }),
    defineField({
      name: 'duration',
      title: 'Tempo de leitura legado',
      type: 'number',
      group: 'technical',
      readOnly: true,
      hidden: ({document}) => document?.duration == null,
    }),
    defineField({
      name: 'mainImage',
      title: 'Imagem principal legada',
      type: 'image',
      group: 'technical',
      readOnly: true,
      hidden: ({document}) => !document?.mainImage,
      fields: [defineField({name: 'alt', title: 'Texto alternativo', type: 'string'})],
      options: {hotspot: true},
    }),
  ],
  preview: {
    select: {title: 'title', media: 'thumbnail'},
    prepare(selection) {
      return {...selection, subtitle: 'VitaCerta'}
    },
  },
})
